let
    Fonte = Excel.CurrentWorkbook(){[Name="Database"]}[Content],

    #"Tipo Alterado" = Table.TransformColumnTypes
    (
        Fonte,
        {
            {"Gerente",                      type any}, 
            {"Nome Gerente",                 type any}, 
            {"Coordenador",                  type any}, 
            {"Nome Coordenador",             type any}, 
            {"Vendedor",                     type any}, 
            {"Nome Vendedor",                type any}, 
            {"Representante",                type any}, 
            {"Nome Representante",           type any}, 
            {"Cod.Cliente",                  Int64.Type}, 
            {"Nome Cliente",                 type text}, 
            {"Cod. Rede",                    type any}, 
            {"Desc. Rede",                   type any}, 
            {"Rua",                          type text}, 
            {"No.",                          Int64.Type}, 
            {"Bairro",                       type text}, 
            {"CEP",                          type text}, 
            {"Cidade",                       type text}, 
            {"UF",                           type text}, 
            {"País",                         type text}, 
            {"Dom.Fiscal",                   type text}, 
            {"Zona Transp.",                 type text}, 
            {"Telefone",                     type text}, 
            {"FAX",                          type text}, 
            {"CNPJ",                         type text}, 
            {"CPF",                          type text}, 
            {"Insc. Estadual",               type text}, 
            {"Insc. Municipal",              type any}, 
            {"Empresa",                      Int64.Type}, 
            {"Grupo de clientes",            Int64.Type}, 
            {"Desc. Grp. de clientes",       type text}, 
            {"Org.Ven.",                     Int64.Type}, 
            {"Can.Dist.",                    Int64.Type}, 
            {"Desc. Can. Dist.",             type text}, 
            {"Set.Ativ.",                    Int64.Type}, 
            {"Cod.MEGA",                     Int64.Type}, 
            {"Reg.Vendas",                   Int64.Type}, 
            {"Desc. Reg. Vendas",            type text}, 
            {"Estado",                       type text}, 
            {"Esc.Vendas",                   type text}, 
            {"Desc. Esc. Vendas",            type text}, 
            {"Set.Vendas",                   Int64.Type}, 
            {"Desc. Set. Vendas",            type any}, 
            {"Lst.Preço",                    type any}, 
            {"Centro",                       type text},
            {"Inco",                         type text}, 
            {"Incoterms",                    type text}, 
            {"Cond.Pagto",                   type text}, 
            {"Área Crédito",                 type text}, 
            {"Limite Crédito",               Int64.Type}, 
            {"Crédito Utilizado",            type number}, 
            {"Status do Cliente",            type text}, 
            {"Data de Cadastro (SAP)",       type date}, 
            {"E-Mail",                       type text}, 
            {"Banco Emp.",                   type any}, 
            {"F. Pgto.",                     type text}, 
            {"Desc. Forma Pagto.",           type text}, 
            {"Cont.",                        Int64.Type},
            {"Última compra",                type date}, 
            {"Termo Pesquisa 1",             type text}, 
            {"Termo Pesquisa 2",             type text}, 
            {"Hora de Receb. Inicio",        Int64.Type}, 
            {"Hora de Receb. Fim",           Int64.Type}, 
            {"Feriados Nacionais",           type any}, 
            {"Feriados Municipais",          type any}, 
            {"Paletizado",                   type any}, 
            {"Seg. - Dias para Receb.",      type any}, 
            {"Ter - Dias para Receb.",       type any}, 
            {"Qua - Dias para Receb.",       type any}, 
            {"Qui - Dias para Receb.",       type any}, 
            {"Sex - Dias para Receb.",       type any}, 
            {"Sab - Dias para Receb.",       type any}, 
            {"Dom - Dias para Receb.",       type any}, 
            {"Tipo Veiculo",                 type any}, 
            {"Agendamento",                  type any}, 
            {"Laudo",                        type any}, 
            {"Mesmo Lote",                   type any}, 
            {"Observação Cliente",           type any}, 
            {"Percentual desconto",          Int64.Type}, 
            {"Dt.Alt.Lim.Cred",              type date}, 
            {"Bloqueio Geral",               type any}, 
            {"Bloqueio Crédito",             type any}, 
            {"Marc.Eliminação",              type any}, 
            {"Grp.Crédito",                  type text}
        }
    ),
    
    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [#"Data de Cadastro (SAP)"] >= #date(2019, 1, 1)),

    #"Colunas Removidas" = Table.RemoveColumns
    (
        #"Linhas Filtradas",
        {
            "Gerente",
            "Nome Gerente",
            "Coordenador",
            "Nome Coordenador",
            "Vendedor",
            "Nome Vendedor",
            "Representante",
            "Nome Representante",
            // "Cod.Cliente",
            // "Nome Cliente",
            "Cod. Rede",
            "Desc. Rede",
            "Rua",
            "No.",
            "Bairro",
            "CEP",
            "Cidade",
            "UF",
            "País",
            "Dom.Fiscal",
            "Zona Transp.",
            "Telefone",
            "FAX",
            // "CNPJ",
            // "CPF",
            "Insc. Estadual",
            "Insc. Municipal",
            "Empresa",
            "Grupo de clientes",
            "Desc. Grp. de clientes",
            "Org.Ven.",
            "Can.Dist.",
            "Desc. Can. Dist.",
            "Set.Ativ.",
            "Cod.MEGA",
            "Reg.Vendas",
            "Desc. Reg. Vendas",
            "Estado",
            "Esc.Vendas",
            "Desc. Esc. Vendas",
            // "Set.Vendas",
            "Desc. Set. Vendas",
            // "Lst.Preço",
            "Centro",
            "Inco",
            "Incoterms",
            "Cond.Pagto",
            "Área Crédito",
            // "Limite Crédito",
            // "Crédito Utilizado",
            "Status do Cliente",
            // "Data de Cadastro (SAP)",
            "E-Mail",
            "Banco Emp.",
            "F. Pgto.",
            "Desc. Forma Pagto.",
            "Cont.",
            // "Última compra",
            "Termo Pesquisa 1",
            "Termo Pesquisa 2",
            "Hora de Receb. Inicio",
            "Hora de Receb. Fim",
            "Feriados Nacionais",
            "Feriados Municipais",
            "Paletizado",
            "Seg. - Dias para Receb.",
            "Ter - Dias para Receb.",
            "Qua - Dias para Receb.",
            "Qui - Dias para Receb.",
            "Sex - Dias para Receb.",
            "Sab - Dias para Receb.",
            "Dom - Dias para Receb.",
            "Tipo Veiculo",
            "Agendamento",
            "Laudo",
            "Mesmo Lote",
            "Observação Cliente",
            "Percentual desconto",
            // "Dt.Alt.Lim.Cred",
            "Bloqueio Geral",
            "Bloqueio Crédito",
            "Marc.Eliminação"
            // "Grp.Crédito",
        }
    ),

    #"Coluna Condicional Adicionada" = Table.AddColumn
    (
        #"Colunas Removidas", 
        "Limite de crédito ultrapassado", 
        each if [Crédito Utilizado] > [Limite Crédito] then [Crédito Utilizado] - [Limite Crédito] else 0
    ),
    
    #"Tipo Alterado Coluna Limite Ultrapassado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada", {{"Limite de crédito ultrapassado", type number}}),

    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Alterado Coluna Limite Ultrapassado",
        {
            "Cod.Cliente", 
            "Nome Cliente", 
            "CNPJ", 
            "CPF", 
            "Set.Vendas", 
            "Lst.Preço", 
            "Limite Crédito", 
            "Crédito Utilizado", 
            "Limite de crédito ultrapassado", 
            "Data de Cadastro (SAP)", 
            "Última compra", 
            "Dt.Alt.Lim.Cred", 
            "Grp.Crédito"
        }
    ),

    #"Linhas Classificadas" = Table.Sort(#"Colunas Reordenadas",{{"Limite de crédito ultrapassado", Order.Descending}})
in
    #"Linhas Classificadas"