let
    Fonte = Excel.Workbook(File.Contents("C:\Users\user\OneDrive\Auditoria\Buaiz SA\Faturamento e Cobrança\2019-12\03. Documentação Base\FBL5N (Original).XLSX"), null, true),
    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],

    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),

    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",
    {
        {"Conta", Int64.Type}, 
        {"Nome 1", type text}, 
        {"Referência", type text}, 
        {"Montante em moeda interna", type number}, 
        {"Nº documento", Int64.Type}, 
        {"Data do documento", type date}, 
        {"Vencimento líquido", type date}, 
        {"Data de compensação", type date}, 
        {"Atribuição", type text}, 
        {"Atraso após vencimento líquido", Int64.Type}, 
        {"Bloqueio pgto.", type text}, 
        {"Cód.Razão Especial", type text}, 
        {"Condições pgto.", type text}, 
        {"Conta do Razão", Int64.Type}, 
        {"Data de lançamento", type date}, 
        {"Data de pagamento", type date}, 
        {"Desconto 1", type text}, 
        {"Doc.compensação", Int64.Type}, 
        {"Doc.faturamento", Int64.Type}, 
        {"FrmPgto", type text}, 
        {"Mont.base desconto", type number}, 
        {"Montante atual d/desconto", Int64.Type}, 
        {"Montante do desconto", Int64.Type}, 
        {"Montante do desc.MI", Int64.Type}, 
        {"Montante Razão", type number}, 
        {"Motivo lçto.inverso", Int64.Type}, 
        {"Numerador juros", type number}, 
        {"Taxa de desconto 1", Int64.Type}, 
        {"Taxa de desconto 2", Int64.Type}, 
        {"Texto", type text}, 
        {"Texto descritivo", type text}, 
        {"Tipo de documento", type text}
    }), 
    
    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([Tipo de documento] = "DB")), 
   
    #"Coluna Tempo até Devolução Adicionada" = Table.AddColumn(#"Linhas Filtradas", "Tempo até devolução", each [Data de compensação] - [Data do documento]), 
   
    #"Tipo Coluna Tempo até Devolução Alterado" = Table.TransformColumnTypes(#"Coluna Tempo até Devolução Adicionada",{{"Tempo até devolução", Int64.Type}}), 
   
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Coluna Tempo até Devolução Alterado",
    {
        "Conta", 
        "Nome 1", 
        "Nº documento", 
        "Tipo de documento", 
        "Referência", 
        "Data do documento", 
        "Data de compensação", 
        "Tempo até devolução", 
        "Montante em moeda interna", 
        "Vencimento líquido", //A partir dessa linha são as colunas que serão detetadas
        "Atribuição", 
        "Conta do Razão", 
        "Data de lançamento", 
        "Data de pagamento", 
        "Doc.compensação",
        "Doc.faturamento", 
        "Texto", 
        "Atraso após vencimento líquido", 
        "Condições pgto.", 
        "Desconto 1", 
        "FrmPgto", 
        "Mont.base desconto", 
        "Montante atual d/desconto", 
        "Montante do desconto", 
        "Montante do desc.MI", 
        "Montante Razão", 
        "Motivo lçto.inverso", 
        "Numerador juros", 
        "Taxa de desconto 1", 
        "Taxa de desconto 2", 
        "Bloqueio pgto.", 
        "Cód.Razão Especial", 
        "Texto descritivo"
    }), 
   
    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Reordenadas",
    {
        //Colunas que foram deletadas para limpar o relatório, mas podem ser úteis
        "Vencimento líquido",
        "Atribuição", 
        "Conta do Razão", 
        "Data de lançamento", 
        "Data de pagamento", 
        "Doc.compensação",
        "Doc.faturamento",
        "Texto",
        //Colunas que foram deletadas porque não acrescetam informação no WP final
        "Atraso após vencimento líquido", 
        "Condições pgto.", 
        "Desconto 1", 
        "FrmPgto", 
        "Mont.base desconto", 
        "Montante atual d/desconto", 
        "Montante do desconto", 
        "Montante do desc.MI", 
        "Montante Razão", 
        "Motivo lçto.inverso", 
        "Numerador juros", 
        "Taxa de desconto 1", 
        "Taxa de desconto 2", 
        "Bloqueio pgto.", 
        "Cód.Razão Especial", 
        "Texto descritivo"
    })

    #"Linhas Classificadas" = Table.Sort(#"Colunas Removidas",{{"Tempo até devolução", Order.Descending}}),
    
    #"Linhas Filtradas1" = Table.SelectRows(#"Linhas Classificadas", each [Tempo até devolução] > 45)
in
    #"Colunas Removidas"