let
    Fonte = Excel.Workbook(File.Contents("C:\Users\user\OneDrive\Auditoria\Buaiz SA\Faturamento e Cobrança\2019-12\03. Documentação Base\FBL5N (Original).XLSX"), null, true), 
    Documentos_Vencidos = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data], 
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Documentos_Vencidos, [PromoteAllScalars=true]),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",
        {
            {"Conta",                           Int64.Type}, 
            {"Nome 1",                          type text}, 
            {"Referência",                      type text}, 
            {"Montante em moeda interna",       type number}, 
            {"Nº documento",                    Int64.Type}, 
            {"Data do documento",               type date}, 
            {"Vencimento líquido",              type date}, 
            {"Data de compensação",             type date}, 
            {"Atribuição",                      type text}, 
            {"Atraso após vencimento líquido",  Int64.Type}, 
            {"Bloqueio pgto.",                  type text}, 
            {"Cód.Razão Especial",              type text}, 
            {"Condições pgto.",                 type text}, 
            {"Conta do Razão",                  Int64.Type}, 
            {"Data de lançamento",              type date}, 
            {"Data de pagamento",               type date}, 
            {"Desconto 1",                      type text}, 
            {"Doc.compensação",                 Int64.Type}, 
            {"Doc.faturamento",                 Int64.Type}, 
            {"FrmPgto",                         type text}, 
            {"Mont.base desconto",              type number}, 
            {"Montante atual d/desconto",       Int64.Type}, 
            {"Montante do desconto",            Int64.Type}, 
            {"Montante do desc.MI",             Int64.Type}, 
            {"Montante Razão",                  type number}, 
            {"Motivo lçto.inverso",             Int64.Type}, 
            {"Numerador juros",                 type number}, 
            {"Taxa de desconto 1",              Int64.Type}, 
            {"Taxa de desconto 2",              Int64.Type}, 
            {"Texto",                           type text}, 
            {"Texto descritivo",                type text}, 
            {"Tipo de documento",               type text}
        }),
    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([Data de compensação] <> null)),  
    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas", "Dias Vencidos", each [Data de compensação]-[Vencimento líquido]),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Dias Vencidos", type number}}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Alterado1",
        {   
            "Conta", 
            "Nome 1", 
            "Referência", 
            "Montante em moeda interna",
            "Nº documento",
            "Tipo de documento",
            "Data do documento", 
            "Vencimento líquido", 
            "Data de compensação", 
            "Dias Vencidos", 
            "Atribuição", 
            "Atraso após vencimento líquido", 
            "Bloqueio pgto.", 
            "Cód.Razão Especial", 
            "Condições pgto.", 
            "Conta do Razão", 
            "Data de lançamento", 
            "Data de pagamento", 
            "Desconto 1", 
            "Doc.compensação", 
            "Doc.faturamento", 
            "FrmPgto", 
            "Mont.base desconto", 
            "Montante atual d/desconto", 
            "Montante do desconto", 
            "Montante do desc.MI", 
            "Montante Razão", 
            "Motivo lçto.inverso", 
            "Numerador juros", 
            "Taxa de desconto 1", 
            "Taxa de desconto 2", 
            "Texto", 
            "Texto descritivo"
        }),
    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Reordenadas", each [Dias Vencidos] < -4),
    #"Linhas Filtradas2" = Table.SelectRows(#"Linhas Filtradas1", each ([Tipo de documento] = "DY")),
    #"Linhas Classificadas" = Table.Sort(#"Linhas Filtradas2",{{"Dias Vencidos", Order.Ascending}}),
    #"Linhas Filtradas4" = Table.SelectRows(#"Linhas Filtradas3", each not Text.Contains([Texto], "CANC"))
in
    #"Linhas Filtradas4"