let
    Fonte = Excel.CurrentWorkbook(){[Name="Tabela2"]}[Content],
   
    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,
        {
            {"Conta",                     Int64.Type}, 
            {"Nome 1",                    type text}, 
            {"Referência",                type text},
            {"Montante em moeda interna", type number}, 
            {"Nº documento",              Int64.Type}, 
            {"Tipo de documento",         type text}, 
            {"Data do documento",         type date}, 
            {"Vencimento líquido",        type date}, 
            {"Ano",                       Int64.Type}, 
            {"Data de compensação",       type date}, 
            {"Atribuição",                type text}, 
            {"Atraso",                    Int64.Type}, 
            {"Categoria",                 type text}, 
            {"Bloqueio pgto.",            type any}, 
            {"Cód.Razão Especial",        type any}, 
            {"Condições pgto.",           type text}, 
            {"Conta do Razão",            Int64.Type}, 
            {"Data de lançamento",        type date}, 
            {"Data de pagamento",         type date}, 
            {"Desconto 1",                type text}, 
            {"Doc.compensação",           type any}, 
            {"Doc.faturamento",           Int64.Type}, 
            {"FrmPgto",                   type text}, 
            {"Mont.base desconto",        type number}, 
            {"Montante atual d/desconto", Int64.Type}, 
            {"Montante do desconto",      Int64.Type}, 
            {"Montante do desc.MI",       Int64.Type}, 
            {"Montante Razão",            type number}, 
            {"Motivo lçto.inverso",       type any}, 
            {"Numerador juros",           type number}, 
            {"Taxa de desconto 1",        Int64.Type}, 
            {"Taxa de desconto 2",        Int64.Type}, 
            {"Texto",                     type text}, 
            {"Texto descritivo",          type text}
        }),
    #"Linhas Inferiores Removidas" = Table.RemoveLastN(#"Tipo Alterado",1),
    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Inferiores Removidas", each ([Tipo de documento] = "DY")),
    #"Linhas Filtradas 1" = Table.SelectRows(#"Linhas Filtradas", each [Atraso] > 5),
    #"Linhas Filtradas 2" = Table.SelectRows(#"Linhas Filtradas 1", each [Ano] = 2019),
    #"Linhas Classificadas" = Table.Sort(#"Linhas Filtradas 2",{{"Categoria", Order.Ascending}}),

    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Classificadas",{"Ano"}),
    #"Índice Adicionado" = Table.AddIndexColumn(#"Colunas Removidas", "Índice", 1, 1),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Índice Adicionado",
        {
            "Índice",
            "Conta",
            "Nome 1",
            "Referência",
            "Montante em moeda interna",
            "Nº documento",
            "Tipo de documento",
            "Data do documento",
            "Vencimento líquido",
            "Data de compensação",
            "Atraso",
            "Atribuição",
            "Categoria",
            "Bloqueio pgto.",
            "Cód.Razão Especial",
            "Condições pgto.",
            "Conta do Razão",
            "Data de lançamento",
            "Data de pagamento",
            "Desconto 1",
            "Doc.compensação",
            "Doc.faturamento",
            "FrmPgto",
            "Mont.base desconto",
            "Montante atual d/desconto",
            "Montante do desconto",
            "Montante do desc.MI",
            "Montante Razão",
            "Motivo lçto.inverso",
            "Numerador juros",
            "Taxa de desconto 1",
            "Taxa de desconto 2",
            "Texto",
            "Texto descritivo"
        })
in
    #"Colunas Reordenadas"